# Generated by Django 3.0.8 on 2020-07-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('instock', 'In Stock'), ('outstock', 'Out Stock')], db_column='status', max_length=50),
        ),
    ]
